[server]
maxUploadSize = 200
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true

[theme]
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"
